name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root deps
        run: |
          npm ci || true

      - name: Install functions deps
        run: |
          cd functions
          npm ci

      - name: Run functions tests
        run: |
          cd functions
          npm test
